ALTER TABLE "MarketSyncState" ADD COLUMN "activeRunId" TEXT;
ALTER TABLE "MarketSyncState" ADD COLUMN "lastRunId" TEXT;

CREATE TABLE "MarketSyncRun" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "stateKey" TEXT NOT NULL,
    "status" TEXT NOT NULL,
    "initialTriggeredBy" TEXT,
    "latestTriggeredBy" TEXT,
    "recoveryKind" TEXT NOT NULL DEFAULT 'none',
    "resumedFromRecovery" BOOLEAN NOT NULL DEFAULT false,
    "currentPhase" TEXT NOT NULL,
    "runStartedAt" DATETIME NOT NULL,
    "latestAttemptStartedAt" DATETIME NOT NULL,
    "latestAttemptFinishedAt" DATETIME,
    "runFinishedAt" DATETIME,
    "lastHeartbeatAt" DATETIME NOT NULL,
    "phaseStartedAt" DATETIME NOT NULL,
    "metricsFlushedAt" DATETIME NOT NULL,
    "attemptCount" INTEGER NOT NULL DEFAULT 1,
    "activeDurationMs" BIGINT NOT NULL DEFAULT 0,
    "pausedDurationMs" BIGINT NOT NULL DEFAULT 0,
    "quotaWaitDurationMs" BIGINT NOT NULL DEFAULT 0,
    "retryBackoffDurationMs" BIGINT NOT NULL DEFAULT 0,
    "pageRequests" INTEGER NOT NULL DEFAULT 0,
    "httpAttempts" INTEGER NOT NULL DEFAULT 0,
    "httpSucceeded" INTEGER NOT NULL DEFAULT 0,
    "httpFailed" INTEGER NOT NULL DEFAULT 0,
    "retryCount" INTEGER NOT NULL DEFAULT 0,
    "timeoutCount" INTEGER NOT NULL DEFAULT 0,
    "emptyResponseCount" INTEGER NOT NULL DEFAULT 0,
    "notFoundCount" INTEGER NOT NULL DEFAULT 0,
    "rateLimitedCount" INTEGER NOT NULL DEFAULT 0,
    "quotaWaitCount" INTEGER NOT NULL DEFAULT 0,
    "latencySampleCount" INTEGER NOT NULL DEFAULT 0,
    "latencyTotalMs" BIGINT NOT NULL DEFAULT 0,
    "latencyMaximumMs" INTEGER NOT NULL DEFAULT 0,
    "latencyLe250Count" INTEGER NOT NULL DEFAULT 0,
    "latencyLe1000Count" INTEGER NOT NULL DEFAULT 0,
    "latencyLe3000Count" INTEGER NOT NULL DEFAULT 0,
    "latencyLe10000Count" INTEGER NOT NULL DEFAULT 0,
    "latencyLe30000Count" INTEGER NOT NULL DEFAULT 0,
    "latencyGt30000Count" INTEGER NOT NULL DEFAULT 0,
    "runQuotaUnitsUsed" INTEGER NOT NULL DEFAULT 0,
    "creditsUsed" REAL NOT NULL DEFAULT 0,
    "configuredConcurrency" INTEGER NOT NULL DEFAULT 0,
    "currentConcurrency" INTEGER NOT NULL DEFAULT 0,
    "minimumConcurrencyUsed" INTEGER NOT NULL DEFAULT 0,
    "peakInFlight" INTEGER NOT NULL DEFAULT 0,
    "concurrencyReductionCount" INTEGER NOT NULL DEFAULT 0,
    "concurrencyIncreaseCount" INTEGER NOT NULL DEFAULT 0,
    "deferredCandidateCount" INTEGER NOT NULL DEFAULT 0,
    "throughputWindowStartedAt" DATETIME,
    "throughputWindowStartValidAssets" INTEGER NOT NULL DEFAULT 0,
    "recentValidAssetsPerMinute" REAL,
    "targetAssets" INTEGER NOT NULL DEFAULT 0,
    "assetsPerItem" INTEGER NOT NULL DEFAULT 0,
    "totalCandidates" INTEGER NOT NULL DEFAULT 0,
    "candidatesVisited" INTEGER NOT NULL DEFAULT 0,
    "rawAssetCount" INTEGER NOT NULL DEFAULT 0,
    "validAssetCount" INTEGER NOT NULL DEFAULT 0,
    "skippedAssetCount" INTEGER NOT NULL DEFAULT 0,
    "publishedListingCount" INTEGER NOT NULL DEFAULT 0,
    "publishedFloatCount" INTEGER NOT NULL DEFAULT 0,
    "snapshotHash" TEXT,
    "completionReason" TEXT,
    "lastError" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
);

CREATE TABLE "MarketSyncPhaseMetric" (
    "runId" TEXT NOT NULL,
    "phase" TEXT NOT NULL,
    "durationMs" BIGINT NOT NULL DEFAULT 0,
    "entryCount" INTEGER NOT NULL DEFAULT 0,
    "lastEnteredAt" DATETIME,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    PRIMARY KEY ("runId", "phase"),
    CONSTRAINT "MarketSyncPhaseMetric_runId_fkey" FOREIGN KEY ("runId") REFERENCES "MarketSyncRun" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE "MarketAssetCandidateHistory" (
    "candidateKey" TEXT NOT NULL PRIMARY KEY,
    "runId" TEXT,
    "queueVersion" TEXT NOT NULL,
    "marketHashName" TEXT NOT NULL,
    "outcome" TEXT NOT NULL,
    "providerTotal" INTEGER NOT NULL DEFAULT 0,
    "rawAssetCount" INTEGER NOT NULL DEFAULT 0,
    "validAssetCount" INTEGER NOT NULL DEFAULT 0,
    "skippedAssetCount" INTEGER NOT NULL DEFAULT 0,
    "pageRequests" INTEGER NOT NULL DEFAULT 0,
    "httpAttempts" INTEGER NOT NULL DEFAULT 0,
    "lastOffset" INTEGER NOT NULL DEFAULT 0,
    "effectiveConcurrency" INTEGER,
    "errorStatus" INTEGER,
    "errorMessage" TEXT,
    "observedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "MarketAssetCandidateHistory_runId_fkey" FOREIGN KEY ("runId") REFERENCES "MarketSyncRun" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE INDEX "MarketSyncRun_stateKey_runStartedAt_idx" ON "MarketSyncRun"("stateKey", "runStartedAt");
CREATE INDEX "MarketSyncRun_status_lastHeartbeatAt_idx" ON "MarketSyncRun"("status", "lastHeartbeatAt");
CREATE INDEX "MarketSyncPhaseMetric_phase_idx" ON "MarketSyncPhaseMetric"("phase");
CREATE INDEX "MarketAssetCandidateHistory_runId_idx" ON "MarketAssetCandidateHistory"("runId");
CREATE INDEX "MarketAssetCandidateHistory_queueVersion_observedAt_idx" ON "MarketAssetCandidateHistory"("queueVersion", "observedAt");
