GET https://api.csgofloat.com/?url=76561198100328935


### 
GET https://steamcommunity.com/inventory/76561198100328935/730/2

####
GET https://steamcommunity.com/inventory/76561198100328935/730/2?l=english&count=5000
Accept: application/json

### Obtener inventario CS2
GET https://steamcommunity.com/inventory/76561198100328935/730/2?l=english&count=5000
Accept: application/json